### ISSUE TITLE
Change calendar page

### ISSUE THREAD

**Issue by CunhaPedro25** [ei-estg/goipvc#154]
The calendar page currently relies on an image, but for better functionality, it should utilize an endpoint. This would allow updates without the need for manual image updates.

**Comment by mattcapazz** [comment]
@CunhaPedro25 any idea where they have this information public, I assume this is the conversation that we had before regarding the pdfs right?

**Comment by joaoalves03** [comment]
@mattcapazz should be this https://www.ipvc.pt/estg/wp-content/uploads/sites/3/2023/04/Calendario_Escolar_IPVC2023_2024.pdf

**Comment by CunhaPedro25** [comment]
Welp apparently there's (from what i saw right now) 2 pdfs: one for general ipvc stuff, and another one specifically for estg, so that creates a bit of a problem cause different schools can apparently have different time periods for exams.
Either that or the ipvc calendar is just wrong.

The one we are using for the image is the general ipvc one that can be find here: https://www.ipvc.pt/wp-content/uploads/2023/04/Calendario-Escolar-2023-24.pdf

But this one conflicts with the specific one for estg that can be found here: https://www.ipvc.pt/estg/wp-content/uploads/sites/3/2023/04/Calendario_Escolar_IPVC2023_2024.pdf

**Comment by mattcapazz** [comment]
problem with the approach that we talked about is that a pdf parser wouldn't be able to parse this as this is an image(photocopy of a document), instead of raw text, therefore the only solution that I see to automatize this without relying on myIPVC API would be OCR or manually inserting it. OCR has the disadvantage that characters might be wrongly identified

**Comment by CunhaPedro25** [comment]
But from what we know right now thats the only place where that information is public, unless there's another place where we can scrape information but that would lead to dependencies from other app or websites, which probably will create problems.

**Comment by joaoalves03** [comment]
I feel like a public endpoint in the new API would be a way to fix this. There could be a way to edit what the API returns (if the calendar changes again).
Any fully automatic solutions feel like a waste of time for me.

**Comment by rodrigosa7** [comment]
So, we just found out that the native API already has an endpoint for the calendar, so our approach here is to get it from there. 
In the future, we should put this in our API and clean the data.
