### ISSUE TITLE
Remake meal cards

### ISSUE THREAD

**Issue by joaoalves03** [ei-estg/goipvc#164]
As of right now, the meal card layout is so horribly done that in some phones it displays huge cards, bigger than space they have available. Not to mention they are also aesthetically unappealing.

**Comment by joaoalves03** [comment]
Need @CunhaPedro25 's screenshots for context.

**Comment by CunhaPedro25** [comment]
![1707062820614.jpg](https://github.com/ei-estg/goipvc/assets/72658683/f6bcebfa-f443-4230-82a7-eea631563fe3)
